# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gefyra < Formula
  desc "Redis bridge for channels and lists."
  homepage "https://github.com/outofcoffee/gefyra"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/outofcoffee/gefyra/releases/download/v0.1.1/gefyra_0.1.1_macOS_x86_64.tar.gz"
      sha256 "67702058378247a09edc0bcaa5de0564dec023e822aa94a20833490b6c9c1b60"

      def install
        bin.install "gefyra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/outofcoffee/gefyra/releases/download/v0.1.1/gefyra_0.1.1_macOS_arm64.tar.gz"
      sha256 "84c664d9621695add73966b23fb9c0ef578cbdb288b2033dbf36f80e72aad290"

      def install
        bin.install "gefyra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/outofcoffee/gefyra/releases/download/v0.1.1/gefyra_0.1.1_Linux_armv6.tar.gz"
      sha256 "60d8cc4e69f0948daa9bb6401209556b3569df879cfb1e74ada6fe86ddfb259e"

      def install
        bin.install "gefyra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/outofcoffee/gefyra/releases/download/v0.1.1/gefyra_0.1.1_Linux_x86_64.tar.gz"
      sha256 "4909113701245b0edf5d696e1b580e4cb5d9317e8f01f170067e0d96590358a7"

      def install
        bin.install "gefyra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/outofcoffee/gefyra/releases/download/v0.1.1/gefyra_0.1.1_Linux_arm64.tar.gz"
      sha256 "9a5126eebe7801b0571286e5ad41a2c57dca9708bb5cccd6e5234849ff0bd9b8"

      def install
        bin.install "gefyra"
      end
    end
  end
end
