# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gefyra < Formula
  desc "Redis bridge for channels and lists."
  homepage "https://github.com/outofcoffee/gefyra"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/outofcoffee/gefyra/releases/download/v0.1.3/gefyra_0.1.3_macOS_x86_64.tar.gz"
      sha256 "db5461640fd2ef5e5899e08cbaf152a623c9d72516799a5930529f1ea87eedd0"

      def install
        bin.install "gefyra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/outofcoffee/gefyra/releases/download/v0.1.3/gefyra_0.1.3_macOS_arm64.tar.gz"
      sha256 "15eb8ded02d0c392189c7bd574da2055e66d1c31fe861cb320197fbd801726c6"

      def install
        bin.install "gefyra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/outofcoffee/gefyra/releases/download/v0.1.3/gefyra_0.1.3_Linux_x86_64.tar.gz"
      sha256 "08630874dd10c2b3a41087161b47297edeb17bc223ec5862f6cec9b59a948641"

      def install
        bin.install "gefyra"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/outofcoffee/gefyra/releases/download/v0.1.3/gefyra_0.1.3_Linux_armv6.tar.gz"
      sha256 "b201a9fd2c6b74c0655c9a6530b60a4fcbb8cd1fca58bf774e7f2ae51d72866b"

      def install
        bin.install "gefyra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/outofcoffee/gefyra/releases/download/v0.1.3/gefyra_0.1.3_Linux_arm64.tar.gz"
      sha256 "eeb54f56c29112750dbb4cd6cd58bbc6333c28005ed0571f49f64b2b6a114e33"

      def install
        bin.install "gefyra"
      end
    end
  end
end
